---
- name: Подключение переменных из vault.yml
  include_vars: "{{ playbook_dir }}/vault.yml"

- name: Проверка, что monitoring_stack_dir указан
  fail:
    msg: "monitoring_stack_dir не указан"
  when: monitoring_stack_dir is not defined

- name: Проверка наличия Docker
  command: docker --version
  register: docker_check
  ignore_errors: true

- name: Установка Docker, если отсутствует
  apt:
    name: docker.io
    state: present
  when: docker_check.rc != 0
  become: true

- name: Проверка наличия встроенного docker compose
  command: docker compose version
  register: docker_compose_check
  ignore_errors: true

- name: Проверка наличия docker-compose (старый вариант)
  command: docker-compose version
  register: docker_compose_old
  ignore_errors: true

- name: Установка docker-compose-plugin, если обе версии отсутствуют
  apt:
    name: docker-compose-plugin
    state: present
  when:
    - docker_compose_check.rc != 0
    - docker_compose_old.rc != 0
  become: true

- name: Определение команды compose
  set_fact:
    docker_compose_cmd: >-
      {{ 'docker compose' if docker_compose_check.rc == 0 else 'docker-compose' }}

- name: Создание директории под стек
  file:
    path: "{{ monitoring_stack_dir }}"
    state: directory
    mode: '0755'

- name: Создание подкаталогов для provisioning
  file:
    path: "{{ monitoring_stack_dir }}/provisioning/datasources"
    state: directory
    mode: '0755'
    recurse: yes

- name: Копирование docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ monitoring_stack_dir }}/docker-compose.yml"

- name: Копирование prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: "{{ monitoring_stack_dir }}/prometheus.yml"

- name: Копирование Grafana datasource.yml
  template:
    src: datasource.yml.j2
    dest: "{{ monitoring_stack_dir }}/provisioning/datasources/datasource.yml"

- name: Запуск стека мониторинга
  shell: "{{ docker_compose_cmd }} up -d"
  args:
    chdir: "{{ monitoring_stack_dir }}"
    executable: /bin/bash
